### ISSUE TITLE
Incompatible file system characters for filenames

### ISSUE THREAD

**Issue by andriodious** [Megatokio/zasm#16]
Some of the filenames here use characters that are OneDrive unfriendly e.g. ')' , '>', '?'

I Archive my work area on OneDrive and it is throwing errors because of the special characters used by some of the files.

**Comment by Megatokio** [comment]
Though this is not a problem of the zasm source, i have removed or renamed those files as far as i could find them. But this will not be forever, because files with uncommon but entirely legal characters may be added anytime again. 

But this should give you the time to issue a bug report where it belongs: at Microsoft.

hth, Kio !
