### ISSUE TITLE
Idea with C compiler.

### ISSUE THREAD

**Issue by turbocat2001** [Megatokio/zasm#28]
Hello, is it possible to generate sdcc i8080 code? I saw your project linked to this compiler. But it seemed to me that he could not in its purest form. I looked into the z88dk project. There's a "picked up and cleaned up" Small C Compiler (
https://github.com/z88dk/z88dk/tree/master/src/sccz80). Which is able not to generate machine code for i8080, but to generate code for their assembler. But I don't like it because it uses the z80 style for the i8080. I like your assembler just for the --asm8080 option. And so I thought whether it is possible to teach them sccz80 to generate code that ZASM will understand.

**Comment by Megatokio** [comment]
I dont understand what you actually want me to do.
If i understand you right you want me to participate in the z88dk project and achieve that their compiler can also emit i8080 assembler code. I think you should ask them there. But i doubt they will. This will add a lot of work with no benefit except for you because the compiler probably directly emits the assembler source and there are certainly some optimizing steps which work on the assembler source which would need to be rewritten. 
If i got you wrong please clarify.

**Comment by turbocat2001** [comment]
All in all, it was a stupid idea. I thought it over well. I don't think it's worth it. Sorry for disturbing you for nothing.

**Comment by Megatokio** [comment]
don't worry. :-)
