### ISSUE TITLE
Question: z88dk-zsdcc labels

### ISSUE THREAD

**Issue by andrisr223** [Megatokio/zasm#29]
I am using the template with C code from the Examples section. When using sdcc (v4.0.0) the project builds fine.
Wanted to compare the generated code with z88dk-zsdcc (from the docker image z88dk provides) and run into issues with labels (below). From zasm documentation I understand that numeric labels ending with $ are supported (and labels including text are not supported). Could not figure out how to (easily) solve this.

Could you give a hint where to start, to add support for such labels in zasm (if this is feasible)?
That is, if z88dk-zsdcc does not differ from sdcc too much.

```txt
in file src:main.c.s:
122: 	jr	Z, l_irq_rx_a_00102$
     	  	                   ^ end of line expected
127: l_irq_rx_a_00102$:
                     ^ unknown instruction
```

The build phase seems to build the C files (though calls z88dk-zsdccp which I renamed to sdccp) and then exits:
```txt
/src # zasm -uwy --z80 -v2 -I /zasm/sdcc/include -L /zasm/sdcc/lib -i ./my-asm-file.asm   -o my-asm-file.bin
+ /opt/z88dk/bin/sdcpp -nostdinc -Wall -std=c11 -I/zasm/sdcc/include/ -I/src/ -obj-ext=.rel -D__SDCC_STACK_AUTO -D__SDCC_CHAR_UNSIGNED -D__SDCC_INT_LONG_REENT -D__SDCC_FLOAT_REENT -D__SDCCCALL=0 -D__SDCC=4_2_0 -D__SDCC_VERSION_MAJOR=4 -D__SDCC_VERSION_MINOR=2 -D__SDCC_VERSION_PATCH=0 -D__SDCC_REVISION=13081 -D__SDCC_z80 -D__STDC_NO_COMPLEX__=1 -D__STDC_NO_THREADS__=1 -D__STDC_NO_ATOMICS__=1 -D__STDC_NO_VLA__=1 -D__STDC_ISO_10646__=201409L -D__STDC_UTF_16__=1 -D__STDC_UTF_32__=1  /src/main.c
```

**Comment by Megatokio** [comment]
this is probably fairly easy. look at asmLabel() and value() in Z80Assembler.cpp.
I was reluctant to accept all names with a trailing '$' as a label name, because the '$' sign is so over-used with many meanings, but as long as nobody comes up with an operator '$' or allow it in the middle of a name, using it as last char in any label name should be ok.

asmLabel() should be straight forward.
value() needs some places to take care of the enhanced names.
also mimik the behavior of value() in skip_expression(), though it is only seldomly used.

format source with clang-format. (though result is not perfect yet...)

make test cases in Test/. run it with zasm -T.

you are welcome to ask any questions, especially as some comments are in German.

Kio !

**Comment by andrisr223** [comment]
Thanks.

With some minor changes in `asmLabel()` and `value()` the code builds with z88dk-zsdcc and zasm.
In `value()` added a match for strings l_...$ as labels which may not be the right way.
Will see whether a better way comes up to warrant a pull request.
